env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/essential
  - airbnb-base
  - "plugin:cypress/recommended"
  - "plugin:chai-friendly/recommended"
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  - "cypress"
  - "chai-friendly"
rules: {}
